import csv
from typing import Dict, List

class POSDataLoader:
    """
    Loads Penn-Treebank POS tags from a CSV file.
    Expected format: Sentence, Token, Tag (or similar)
    Or maybe a mapping of known tokens to tags?
    
    If the user means "Validation Data" to act as the fallback or 'correct' model:
    We can load the CSV generated by this tool (disagreements.csv) or a curated one.
    """
    
    def __init__(self, csv_file: str):
        self.csv_file = csv_file
        self.data = {} # Map: Sentence -> List of (Token, Tag)

    def load(self):
        try:
            with open(self.csv_file, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    # Assuming columns like 'sentence', 'model_b' (which contains tags)
                    # This is specific to our logging format. 
                    # If the user provides a different format, we adjust.
                    sentence = row.get('sentence')
                    if not sentence:
                        continue
                        
                    # For now, let's assume we load the 'Correct' tags from a column
                    # If it's from our logs, 'result_b' has the list of tuples string.
                    import ast
                    if 'result_b' in row:
                        try:
                            tags = ast.literal_eval(row['result_b'])
                            self.data[sentence] = tags
                        except:
                            pass
        except FileNotFoundError:
            print(f"POS Data file not found: {self.csv_file}")

    def get_tags(self, sentence: str) -> List[Tuple[str, str]]:
        return self.data.get(sentence, [])

